service: sls-notes-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:us-east-1:*:table/sls-notes-backend"

functions:
  createNote:
    handler: handler.createNote
    events:
      - http:
          path: note
          method: post
          cors: true

  getAllNotes:
    handler: handler.getAllNotes
    events:
      - http:
          path: notes
          method: get
          cors: true

  getNote:
    handler: handler.getNote
    events:
      - http:
          path: note/{id}
          method: get
          cors: true

  deleteNote:
    handler: handler.deleteNote
    events:
      - http:
          path: note/{id}
          method: delete
          cors: true

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sls-notes-backend
        AttributeDefinitions:
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: noteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
